[package]
name = "ethereum_abi"
version = "0.1.0"
authors = ["Felipe Rosa <felipe.sgrosa@gmail.com>"]
edition = "2018"

[dependencies]
ethereum-types = "0.9.2"
nom = "6.0.1"
regex = "1.4.2"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }

[dev-dependencies]
hex = "0.4.2"
pretty_assertions = "0.6.1"
rand = "0.7.3"